A little Change for Better Korean.
fengberd/MinecraftPEServer pull request #45
Opened 2016-11-09 16:29 UTC by cws06099

Hello, I'm Moon Night(cws06099@gmail.com)

So far, I didn't know what to do until I learned how to do it(Pull Request).
So I request the request of this account.

I modified a little bit for a better Korean translation.
Please accept my pull request.

Thank you.

2016-11-09 18:24 UTC, ParkChanSol commented
I don't agree with your PRs
PHP7 LOAD IS NOT SAME PHP7 DOWNLOAD

2016-11-09 18:28 UTC, nnnlog requested changes
GMT 는 UTC 와 몇 초의 차이 밖에 나지 않으니 굳이 개선될 필요는 없다봅니다

2016-11-09 22:43 UTC, cws06099 commented
거슬려서 바꾼거라서 신경 안쓰셔도되긴한데, 단어가 다운로드로 안바뀌는게 문제라서 못바꿉니다. 그래서 어쩔수없이 로드라고 변경되있는거구요.

2016-11-09 22:46 UTC, cws06099 commented
I can't change ' load ' to ' download '. The reason for this is that I don't not know whether Github is a problem or not.

2016-11-09 22:53 UTC, cws06099 commented
No matter how many times it tries, ' load ' will not be changed to download. No matter what ‘ load ’ from the server, there is no problem in translation.

2016-11-09 22:57 UTC, nnnlog requested changes
그렇다면 'PHP7 다운 및 설치 중'문구로 개선해도 될듯합니다

2016-11-09 22:58 UTC, cws06099 commented
Ok I got it

2016-11-10 07:13 UTC, nnnlog approved these changes
좋습니다 :)
It looks good~

2016-11-11 12:57 UTC, Johnmacrocraft commented
@cws06099 PHP7 다운에서 다운로드가 굳이 다운으로 변경되야 할까요? 물론 다운이라고 해도 세상 물정 모르는 분이 아니라면 대부분 다 알아 듣겠지만, 그래도 제 의견으로는 이전처럼 다운로드가 괜찮다고 생각합니다. 또한, 번역에 레딧이 들어갔는데, 진짜로 인정을 받야하는 경우가 아니면 제거하는 것도 좋다고 생각합니다. (그렇게 말하고 정작 자신은 자신 이름과 @ParkChanSol님 이름을 Genisys 한국어 번역에 넣어놓은 1인 XD)

2016-11-11 13:06 UTC, ParkChanSol commented
@Johnmacrocraft 그렇게 @Johnmacrocraft 가 번역함 이라 적어놓은 1ㅅ

@cws06099 제 생각도 똑같습니다.
굳이 자신이 번역했다고 알릴 필요는 없다 봅니다

2016-11-11 13:08 UTC, nnnlog requested changes
번역자 주석을 지워주심을 권장드립니다.

님이 하시지 않더라도 전 후에 PR을 통해 지울 것입니다

2016-11-11 13:08 UTC, ParkChanSol commented on app/src/main/res/values-ko/strings.xml
> +<!-- Translated By. Moon Night(cws06099@gmail.com) -->
번역자 주석은 지워주십시오

2016-11-11 13:35 UTC, cws06099 commented
누가 번역했는지 쯤은 남겨둬야지요.
그리고, 다운로드로 변경이 안된다고 말한지 몇번 됬는데 말입니다.

2016-11-11 13:40 UTC, ParkChanSol commented
@cws06099 다운로드로 변경이 안된다는것은 앱의 문제이므로 issue 에 제보해야 맞습니다.
또한, 누가 번역했는지는 이미 앱 릴리즈에 님이 한 게 나와있는것도 모자라나요?

2016-11-11 13:41 UTC, cws06099 commented
앱 릴리즈에 나오는건 잠시뿐이고요, 이건 앱 문제가 아니라 깃허브 문제입니다.

2016-11-11 13:44 UTC, ParkChanSol commented
@cws06099 무슨 소린지 모르겠네요, 님이 번역했음에도 불구하고 앱애서 잘못뜨는것 앱 문제입니다

2016-11-11 13:44 UTC, cws06099 commented
아니; 깃허브상에서 수정해서 확인해보면 분명 다운로드 라고 썼으나 로드 글자가 증발한다니까요?
앱 문제일리도 없고 문제일수도 없습니다

2016-11-11 13:48 UTC, ParkChanSol commented
@cws06099 제가 수정해서 되면요?

2016-11-11 13:50 UTC, cws06099 commented
확인해보세요.

2016-11-11 14:19 UTC, Johnmacrocraft commented
@cws06099 혹시 Github 온라인 수정기로 파일을 수정하셨다면, 메모장을 열고 그 내용을 복사하고 로드를 넣어서 다시 올려보시면 안될까요?

2016-11-11 23:20 UTC, cws06099 commented
@Johnmacrocraft 흠..새로운 해결방안이네요. 한번 해보겠습니다. 조언 감사합니다

2016-11-13 04:49 UTC, fengberd commented
Why did you change GMT +9 to UTC +9....

2016-11-13 04:57 UTC, cws06099 commented
This is a formal reason.I mean, there's no other way...:(

2016-11-13 05:02 UTC, cws06099 commented
I've just finished all this work.

2016-11-13 05:23 UTC, ParkChanSol commented
@cws06099 DO NOT SPAM COMMENT

2016-11-13 15:42 UTC, fengberd commented
Please modify all of these in ONE COMMIT and open a new pr.

2016-11-13 15:42 UTC, closed without merging